const PERMS = {
  VIEW_MAP: "VIEW_MAP",
  BUY_MARKET: "BUY_MARKET",
  VIEW_MARKET: "VIEW_MARKET",
  VIEW_AUCTIONS: "VIEW_AUCTIONS",
  VIEW_EVENTS: "VIEW_EVENTS",
  ENTER_GIVEAWAY: "ENTER_GIVEAWAY",
  SELL_MARKET: "SELL_MARKET",
  POST_CHANNEL: "POST_CHANNEL",
  VIEW_CHANNELS: "VIEW_CHANNELS",
  COMMENT_CHANNELS: "COMMENT_CHANNELS",
  MODERATE_CHANNELS: "MODERATE_CHANNELS",
  CREATE_LISTING: "CREATE_LISTING",
  MESSAGE: "MESSAGE",
  MODERATE_CHANNEL: "MODERATE_CHANNEL",
  APPROVE_EVENTS: "APPROVE_EVENTS",
  INVENTORY_UPLOAD: "INVENTORY_UPLOAD",
  DONATE_GIVEAWAY: "DONATE_GIVEAWAY",
  ADMIN: "ADMIN"
};

const TIER_NAMES = {
  0: "Visitor",
  1: "Verified Visitor",
  2: "Verified Resident",
  3: "Moderator",
  4: "Local Business",
  5: "Admin"
};

function tierToPerms(tier){
  const t = Number(tier) || 0;
  if(t >= 5) return Object.values(PERMS);
  if(t === 4) return [
    PERMS.VIEW_MAP, PERMS.BUY_MARKET, PERMS.VIEW_MARKET, PERMS.VIEW_AUCTIONS,
    PERMS.VIEW_EVENTS, PERMS.ENTER_GIVEAWAY,
    PERMS.VIEW_CHANNELS, PERMS.COMMENT_CHANNELS, PERMS.MODERATE_CHANNELS,
    PERMS.SELL_MARKET, PERMS.POST_CHANNEL, PERMS.CREATE_LISTING, PERMS.MESSAGE,
    PERMS.MODERATE_CHANNEL, PERMS.APPROVE_EVENTS, PERMS.INVENTORY_UPLOAD, PERMS.DONATE_GIVEAWAY
  ];
  if(t === 3) return [
    PERMS.VIEW_MAP, PERMS.BUY_MARKET, PERMS.VIEW_MARKET, PERMS.VIEW_AUCTIONS,
    PERMS.VIEW_EVENTS, PERMS.ENTER_GIVEAWAY,
    PERMS.VIEW_CHANNELS, PERMS.COMMENT_CHANNELS, PERMS.MODERATE_CHANNELS,
    PERMS.SELL_MARKET, PERMS.POST_CHANNEL, PERMS.CREATE_LISTING, PERMS.MESSAGE,
    PERMS.MODERATE_CHANNEL, PERMS.APPROVE_EVENTS
  ];
  if(t === 2) return [
    PERMS.VIEW_MAP, PERMS.BUY_MARKET, PERMS.VIEW_MARKET, PERMS.VIEW_AUCTIONS,
    PERMS.VIEW_EVENTS, PERMS.ENTER_GIVEAWAY,
    PERMS.VIEW_CHANNELS, PERMS.COMMENT_CHANNELS,
    PERMS.SELL_MARKET, PERMS.POST_CHANNEL, PERMS.CREATE_LISTING, PERMS.MESSAGE
  ];
  if(t === 1) return [
    PERMS.VIEW_MAP, PERMS.BUY_MARKET, PERMS.VIEW_MARKET, PERMS.VIEW_AUCTIONS,
    PERMS.VIEW_EVENTS, PERMS.ENTER_GIVEAWAY,
    PERMS.VIEW_CHANNELS
  ];
  return [PERMS.VIEW_MAP];
}

function hasPerm(user, perm){
  if(!user) return false;
  const adminFlag = user.isAdmin ?? user.isadmin;
  if(adminFlag === true || Number(adminFlag) === 1) return true;
  const perms = tierToPerms(user.trustTier);
  return perms.includes(perm);
}

function tierName(tier){
  const t = Number(tier) || 0;
  return TIER_NAMES[t] || TIER_NAMES[0];
}

module.exports = { PERMS, hasPerm, tierToPerms, tierName };
